### ISSUE TITLE
Almost no free engines in the new version, here's a suggestion

### ISSUE THREAD

**Issue by C-E-L-E-S-T-A** [nature-heart-software/izabela#631]
I recently found a great site with a free tts bot, not sure about it yet, but I wish it was in Isabella with languages support. It's just that the old Isabella app has a free api key for Google tts, and the new version is unusable for me, because it doesn't speak languages other than English. Here is https://texttospeechrobot.com/

Also, It would be nice to have a dark theme too. But thank you for having something to talk with friends through!🥰

**Comment by Wurielle** [comment]
Sorry for the late reply, GitHub didn't notify me about new issues for some reasons..
From what I see this TTS doesn't provide a public API that could be used unfortunately..

If you want to use free options, here's what I recommend:

- Say uses (SAPI) voices installed on your PC so if you want to use a voice in your language you might be able to install one either through windows or a third-party software

- If you want more options but want to keep it free, you can create your own API Key for all the available services as most of them offer a generous free tier that will end up costing nothing at the end of the day (or a few cents at best). The only downside is that a payment method is required 
See guides: https://github.com/nature-heart-software/izabela/wiki

- Izabela supports custom APIs as well. There's a provided example at the root of the repo to show how to implement one. You can implement any TTS software you wish to have in any language so you have control of what you can use
See example: https://github.com/nature-heart-software/izabela/tree/dev/examples/custom-engine-api

I will only implement TTS services that I can maintain backed with great support for developers as I had many issues with that in the legacy version of Izabela and I do not wish to make the same mistake again. Still, I provide a lot of fair alternatives for those who want a free or custom experience.

**Comment by C-E-L-E-S-T-A** [comment]
Well thank you, I wish I knew all this programming things, but I would like to try, is there any chance to make that site as a "custom API", edit those examples and put them in Izabela's folder?

**Comment by Wurielle** [comment]
It would be if the website provided some sort of API besides a webpage but it doesn't seem to be the case unfortunately. 
If you find a TTS software with a public API there's a really good chance it can be implemented as a custom API however.
