### ISSUE TITLE
Is there a way to disable the background dim?

### ISSUE THREAD

**Issue by ztgasdf** [nature-heart-software/izabela#633]
It's a bit distracting in intense moments and I'm wondering if there's any way to disable it.

**Comment by Wurielle** [comment]
The overlay is there to make sure there aren't accidental mouse movements that could trigger a window blur (loss of focus). By experience, this can be more annoying than having a dark overlay appearing everytime you want to type.

I can either:
- Implement a slider that lets you choose the opacity of the overlay but if the opacity is too low (near 0), you may not notice when the text input is focused and when it's not (which is also annoying)
- Allow you to disable the overlay entirely when the window appears but the slightest mouse movement may cause a loss of focus and you'll have to focus the text input manually again

**Comment by ztgasdf** [comment]
The game I usually play (CS:S) doesn't have any issues with loss of focus so the latter option would be appreciated.

**Comment by Wurielle** [comment]
Implemented in alpha-26
