### ISSUE TITLE
Izabela does not grab focus on the text bar when shortcut is used

### ISSUE THREAD

**Issue by Aida-Enna** [nature-heart-software/izabela#634]
Hello! Long time user of Izabela V1 and I saw this and thought I would give it a shot. I love the work you've done! However, when I hit ctrl + enter, Izabela doesn't focus on the text bar, so I have to click the text bar manually, then type. The screen also does not dim until I click on the text bar, nor does Izabela take the focus from the window I was on previously.

Fresh Windows 11 install

**Comment by Aida-Enna** [comment]
Video of the issue:
https://github.com/nature-heart-software/izabela/assets/5483362/5a69eb1d-6f60-40cb-b39e-708b595b7ca1

**Comment by Aida-Enna** [comment]
Haha, reading is difficult. The instructions specifically say that ctrl + space will not focus the window. My bad!

**Comment by Wurielle** [comment]
Thank you for trying out this version! 

The compatibility shortcut is best use in case some softwares completely block Electron's shortcut system (e.g: League of Legends) and the first shortcut doesn't work as the result.

If you can I recommend using the first shortcut even though I know changing the shortcut doesn't work perfectly work for every combination.

I'm still gonna try to make both work as intended in the future but currently, some limitation makes it so I can't focus the window after showing it with the second shortcut unfortunately. 😢
