### ISSUE TITLE
Valorant Game minimizes as I open izabela

### ISSUE THREAD

**Issue by back2Lobby** [nature-heart-software/izabela#668]
I just tried this tool with Valorant game, but when I open it with (both) shortcuts during the game, it does open but it also minimizes the game. Any clue if there is something wrong on my end? 

I am using:
Window 10, 12 GB Ram and Nvidia GTX 1050Ti

**Comment by Wurielle** [comment]
Hey there, sorry for the late reply.. 

Are you playing Valorant in fullscreen by any chance? Izabela only works if no other application is in fullscreen.

**Comment by back2Lobby** [comment]
> Hey there, sorry for the late reply..
> 
> Are you playing Valorant in fullscreen by any chance? Izabela only works if no other application is in fullscreen.

ah mb. I did have a clue about that but didn't try it earlier. Now I switched to "Windowed FullScreen" mode and it's working perfectly fine. Thanks for your time 💖

**Comment by Wurielle** [comment]
My pleasure, have fun with the software! ❤️
