### ISSUE TITLE
ElevenLabs voices update on July 11 (Legacy Voices)

### ISSUE THREAD

**Issue by C-E-L-E-S-T-A** [nature-heart-software/izabela#694]
After that update the "legacy" voices are gone.
But there is a way to get them back I guess, please add an option to isabela "Show Legacy Voices"

https://www.reddit.com/r/ElevenLabs/comments/1e00gbo/important_elevenlabs_default_voices_update_on/
> API developers using the GET /v1/voices endpoint will need to add "show_legacy: true" to requests for the Legacy Voices to be listed in the response.

**Comment by Wurielle** [comment]
Thank you for the link and the heads up! This should be available in the next version 😊
